name: CI
on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  push:
    branches:
      - develop
      - feature/*
      - master

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Select Xcode_12_beta
        run: sudo xcode-select -s /Applications/Xcode_12_beta.app
      - name: Run tests
        run:  |
          make test
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Select Xcode_12_beta
        run: sudo xcode-select -s /Applications/Xcode_12_beta.app
      - name: Build
        run:  |
          make build
        env: 
         destination: ${{ matrix.destination }}