name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Select Xcode 12 beta
        run: sudo xcode-select -s /Applications/Xcode_12_beta.app
      - name: Run tests
        run:  |
          make test
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Select Xcode 12 beta
        run: sudo xcode-select -s /Applications/Xcode_12_beta.app
      - name: Build
        run:  |
          make build
        env: 
         destination: ${{ matrix.destination }}